### ISSUE TITLE
Splitting headers in order to have single modules functions

### ISSUE THREAD

**Issue by Rinnegatamante** [vitasdk/vita-headers#274]
This is something required for properly implementing https://github.com/vitasdk/vita-headers/issues/124 .

At the moment we have some headers that actually contain functions from several modules like:

psp2/videodec.h having sceAvcdec and sceVideodec functions.
psp2/net/http.h having sceHttp and sceHttps functions.

Actually splitting headers shouldn't bother too much since the suggested way to use headers is actually to just include vitasdk.h without cherry picking headers.

**Comment by devnoname120** [comment]
> Actually splitting headers shouldn't bother too much **since the suggested way** to use headers is actually to just include vitasdk.h

Most people are not doing that, and we can't afford to break them.

**Comment by Rinnegatamante** [comment]
That means we can't actually ship decent and accurated documentation due to some people preferring to make their life harder.

P.s. I don't see "most" people using these headers btw.
Majority of homebrews cherry picking headers are very old homebrews.
Also replacing such headers with vitasdk.h is an easy enough change even for a non developer.

**Comment by devnoname120** [comment]
The drawbacks largely overwhelm the small benefit such a change would bring. We now don't any kind of breaking changes unless it is absolutely necessary.

**Comment by yne** [comment]
Fun fact, there is only 1 usage of the HTTPS Vita API on github:
https://github.com/Stary2001/vita-lua/blob/1a179629a9068f98154edbce87aef7b0537e826d/src/ffi/http.c

Issues like this should be resolved in a democratic way (it should be less frustrating for both sides).

Personally, I vote to split, because I'm the one that made a mistake back in the psp2sdk days (https://github.com/173210/psp2sdk/commit/e72bf40f0354a4daceee813dca4229cd97e80996) and I don't like doing mistakes.

The official SDK also have them split (net/http.h+net/https.h, avdec.h+videodec.h) so we should split them, not because of the doxygen/documentation but because the SCE SDK should be considered as a reference when conflict like this arise.

**Comment by CelesteBlue-dev** [comment]
@Rinnegatamante "Il n'y a que les cons qui ne changent pas d'avis"
I like seeing you improving the SDK.
Please, now that I have leaked the official 3.55 SDK, look into official headers and copy the more you can into vitasdk.

**Comment by devnoname120** [comment]
@CelesteBlue-dev Please abstain from calling people names, especially for no good reason.
